import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";

import { createCanvas, loadImage } from "@napi-rs/canvas";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import {
  MASK_HEIGHT,
  MASK_WIDTH,
  portraitMaskPng,
} from "./build-portrait-mask";

const maskPath = resolve("public/portrait-particle-mask.png");
const scriptPath = resolve("scripts/build-portrait-mask.ts");
const tsxPath = resolve("node_modules/tsx/dist/cli.mjs");
let temporaryDirectory: string;
let temporaryMaskPath: string;

beforeEach(() => {
  temporaryDirectory = mkdtempSync(join(tmpdir(), "portrait-mask-test-"));
  temporaryMaskPath = join(temporaryDirectory, "portrait-mask.png");
});

afterEach(() => {
  rmSync(temporaryDirectory, { recursive: true, force: true });
});

function runCli(args: string[] = []) {
  return spawnSync(process.execPath, [tsxPath, scriptPath, ...args], {
    cwd: temporaryDirectory,
    encoding: "utf8",
    env: {
      ...process.env,
      PORTRAIT_MASK_OUTPUT: temporaryMaskPath,
    },
  });
}

describe.sequential("portrait particle mask", () => {
  it("rejects unsupported CLI arguments with actionable usage", () => {
    const result = runCli(["--unsupported"]);

    expect(result.status).not.toBe(0);
    expect(`${result.stdout}\n${result.stderr}`).toContain(
      "Usage: tsx scripts/build-portrait-mask.ts [--verify]",
    );
  });

  it("has a committed generated asset", () => {
    expect(existsSync(maskPath)).toBe(true);
  });

  it("matches the deterministic generator byte for byte", () => {
    expect(portraitMaskPng().equals(readFileSync(maskPath))).toBe(true);
  });

  it("has the expected dimensions and subject-only alpha", async () => {
    const image = await loadImage(readFileSync(maskPath));
    expect([image.width, image.height]).toEqual([MASK_WIDTH, MASK_HEIGHT]);

    const canvas = createCanvas(MASK_WIDTH, MASK_HEIGHT);
    const context = canvas.getContext("2d");
    context.drawImage(image, 0, 0);

    const alphaAt = (normalizedX: number, normalizedY: number): number => {
      const x = Math.round(normalizedX * (MASK_WIDTH - 1));
      const y = Math.round(normalizedY * (MASK_HEIGHT - 1));
      return context.getImageData(x, y, 1, 1).data[3]!;
    };

    expect(alphaAt(0.05, 0.05)).toBe(0);
    expect(alphaAt(0.93, 0.48)).toBe(0);
    expect(alphaAt(0.98, 0.65)).toBe(0);
    expect(alphaAt(0.5, 0.34)).toBe(255);
    expect(alphaAt(0.5, 0.6)).toBe(255);
    expect(alphaAt(0.5, 0.9)).toBe(255);
  });

  it("reports an actionable error when the isolated mask is missing", () => {
    const result = runCli(["--verify"]);

    expect(result.status).not.toBe(0);
    expect(`${result.stdout}\n${result.stderr}`).toContain(
      "Portrait particle mask is missing. Run `npm run portrait-mask:generate` to create it.",
    );
    expect(existsSync(temporaryMaskPath)).toBe(false);
  });

  it("generates the exact deterministic bytes in isolation", () => {
    const result = runCli();

    expect(result.status, result.stderr).toBe(0);
    expect(result.stdout.trim()).toBe(
      `Generated portrait particle mask: ${MASK_WIDTH}x${MASK_HEIGHT}`,
    );
    expect(readFileSync(temporaryMaskPath).equals(portraitMaskPng())).toBe(true);
  });

  it("verifies the exact isolated generated bytes", () => {
    writeFileSync(temporaryMaskPath, portraitMaskPng());
    const result = runCli(["--verify"]);

    expect(result.status, result.stderr).toBe(0);
    expect(result.stdout.trim()).toBe(
      `Verified portrait particle mask: ${MASK_WIDTH}x${MASK_HEIGHT}`,
    );
  });

  it("reports actionable drift without changing the tracked asset", () => {
    writeFileSync(
      temporaryMaskPath,
      Buffer.concat([portraitMaskPng(), Buffer.from([0])]),
    );
    const result = runCli(["--verify"]);

    expect(result.status).not.toBe(0);
    expect(`${result.stdout}\n${result.stderr}`).toContain(
      "Portrait particle mask has drifted. Run `npm run portrait-mask:generate` and commit the regenerated asset.",
    );
  });
});
