import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";

import { createCanvas, loadImage } from "@napi-rs/canvas";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import {
  MASK_HEIGHT,
  MASK_WIDTH,
  portraitMaskPng,
} from "./build-portrait-mask";

const maskPath = resolve("public/portrait-particle-mask.png");
const canonicalMaskPath = resolve("scripts/assets/portrait-subject-mask.png");
const scriptPath = resolve("scripts/build-portrait-mask.ts");
const tsxPath = resolve("node_modules/tsx/dist/cli.mjs");
let temporaryDirectory: string;
let temporaryMaskPath: string;

const requiredSubjectPoints = [
  [689, 206, "hair crown"],
  [533, 510, "left glasses and eye"],
  [733, 510, "right glasses and eye"],
  [593, 815, "chin"],
  [658, 930, "Adam's apple"],
  [673, 1030, "collar"],
  [120, 1220, "completed left upper arm"],
  [1180, 1220, "completed right upper arm"],
  [675, 1400, "lower garment"],
] as const;

const forbiddenEnvironmentPoints = [
  [0, 1220, "left edge"],
  [1349, 1220, "right edge"],
  [70, 900, "above left shoulder"],
  [1260, 900, "above right shoulder"],
  [1315, 1050, "far-right background"],
  [67, 71, "upper-left wall"],
  [162, 641, "left furniture"],
  [1214, 797, "right background gap"],
  [1241, 1068, "foreign arm seam above repair"],
  [1309, 968, "raised foreign forearm"],
  [1309, 1282, "foreign black sleeve"],
] as const;

beforeEach(() => {
  temporaryDirectory = mkdtempSync(join(tmpdir(), "portrait-mask-test-"));
  temporaryMaskPath = join(temporaryDirectory, "portrait-mask.png");
});

afterEach(() => {
  rmSync(temporaryDirectory, { recursive: true, force: true });
});

function runCli(args: string[] = []) {
  return spawnSync(process.execPath, [tsxPath, scriptPath, ...args], {
    cwd: temporaryDirectory,
    encoding: "utf8",
    env: {
      ...process.env,
      PORTRAIT_MASK_SOURCE: canonicalMaskPath,
      PORTRAIT_MASK_OUTPUT: temporaryMaskPath,
    },
  });
}

describe.sequential("portrait particle mask", () => {
  it("rejects unsupported CLI arguments with actionable usage", () => {
    const result = runCli(["--unsupported"]);

    expect(result.status).not.toBe(0);
    expect(`${result.stdout}\n${result.stderr}`).toContain(
      "Usage: tsx scripts/build-portrait-mask.ts [--verify]",
    );
  });

  it("has a committed generated asset", () => {
    expect(existsSync(maskPath)).toBe(true);
  });

  it("has a committed canonical subject mask", () => {
    expect(existsSync(canonicalMaskPath)).toBe(true);
  });

  it("matches the deterministic generator byte for byte", () => {
    expect(portraitMaskPng().equals(readFileSync(maskPath))).toBe(true);
  });

  it("retains required identity and clothing points while excluding the environment", async () => {
    const image = await loadImage(readFileSync(maskPath));
    expect([image.width, image.height]).toEqual([1350, 1425]);

    const canvas = createCanvas(MASK_WIDTH, MASK_HEIGHT);
    const context = canvas.getContext("2d");
    context.drawImage(image, 0, 0);

    const alphaAt = (x: number, y: number): number => {
      return context.getImageData(x, y, 1, 1).data[3]!;
    };

    for (const [x, y, label] of requiredSubjectPoints) {
      expect(alphaAt(x, y), label).toBeGreaterThan(200);
    }
    for (const [x, y, label] of forbiddenEnvironmentPoints) {
      expect(alphaAt(x, y), label).toBe(0);
    }
  });

  it("reports an actionable error when the isolated mask is missing", () => {
    const result = runCli(["--verify"]);

    expect(result.status).not.toBe(0);
    expect(`${result.stdout}\n${result.stderr}`).toContain(
      "Portrait particle mask is missing. Run `npm run portrait-mask:generate` to create it.",
    );
    expect(existsSync(temporaryMaskPath)).toBe(false);
  });

  it("generates the exact deterministic bytes in isolation", () => {
    const result = runCli();

    expect(result.status, result.stderr).toBe(0);
    expect(result.stdout.trim()).toBe(
      `Generated portrait particle mask: ${MASK_WIDTH}x${MASK_HEIGHT}`,
    );
    expect(readFileSync(temporaryMaskPath).equals(portraitMaskPng())).toBe(true);
  });

  it("verifies the exact isolated generated bytes", () => {
    writeFileSync(temporaryMaskPath, portraitMaskPng());
    const result = runCli(["--verify"]);

    expect(result.status, result.stderr).toBe(0);
    expect(result.stdout.trim()).toBe(
      `Verified portrait particle mask: ${MASK_WIDTH}x${MASK_HEIGHT}`,
    );
  });

  it("reports actionable drift without changing the tracked asset", () => {
    writeFileSync(
      temporaryMaskPath,
      Buffer.concat([portraitMaskPng(), Buffer.from([0])]),
    );
    const result = runCli(["--verify"]);

    expect(result.status).not.toBe(0);
    expect(`${result.stdout}\n${result.stderr}`).toContain(
      "Portrait particle mask has drifted. Run `npm run portrait-mask:generate` and commit the regenerated asset.",
    );
  });
});
